"""
Generates the Python preamble injected before LLM-generated code.
Uses chr() for all special characters to avoid escape sequence issues.
Includes smart paragraph detection that filters out Wikipedia navigation junk.
"""


def build_preamble(data_file_path: str) -> str:
    """Build a comprehensive preamble that sets up PREV_OUTPUT, PARAGRAPHS, etc."""
    L = []
    L.append("# === Auto-injected by Pilot ===")
    L.append("import re as _re")
    L.append("import json as _json")
    L.append("import os as _os")
    L.append("")
    L.append(f"with open(r'{data_file_path}', 'r', encoding='utf-8') as _f:")
    L.append("    PREV_OUTPUT = _f.read()")
    L.append("")
    L.append("EXTRACTED_TEXT = PREV_OUTPUT")
    L.append("")
    L.append("# Smart paragraph extraction — skips Wikipedia nav, headers, references")
    L.append("def _extract_paragraphs(text):")
    L.append("    _NL = chr(10)")
    L.append("    _CR = chr(13)")
    L.append("    text = text.replace(_CR + _NL, _NL).replace(_CR, _NL)")
    L.append("    parts = _re.split(_NL + _NL, text)")
    L.append("    result = []")
    L.append("    for p in parts:")
    L.append("        p = p.strip()")
    L.append("        if not p or len(p) < 80:")
    L.append("            continue")
    L.append("        # Skip Wikipedia section headers")
    L.append("        if '[edit]' in p:")
    L.append("            continue")
    L.append("        # Skip known non-content sections")
    L.append("        if p.startswith(('vte', 'Categories:', 'See also', 'References[', 'Further reading', 'External links', 'Notes[')):")
    L.append("            continue")
    L.append("        # Skip nav blocks: many short lines = not a paragraph")
    L.append("        lines = [l.strip() for l in p.split(_NL) if l.strip()]")
    L.append("        avg_line_len = sum(len(l) for l in lines) / max(len(lines), 1)")
    L.append("        if avg_line_len < 30 and len(lines) > 3:")
    L.append("            continue")
    L.append("        # Must contain at least one real sentence (period/!/? followed by space or end)")
    L.append("        if not _re.search(r'[.!?](\\s|\\[|$)', p):")
    L.append("            continue")
    L.append("        # Skip reference-style lines")
    L.append("        if p.startswith('^'):")
    L.append("            continue")
    L.append("        result.append(p)")
    L.append("    return result")
    L.append("")
    L.append("PARAGRAPHS = _extract_paragraphs(PREV_OUTPUT)")
    L.append("")
    L.append("# Pre-compute first 3 paragraphs (what tasks usually need)")
    L.append("FIRST_3_PARAGRAPHS = PARAGRAPHS[:3]")
    L.append("FIRST_3_TEXT = (chr(10) + chr(10)).join(FIRST_3_PARAGRAPHS)")
    L.append("")
    L.append("# Helper: remove citation markers [1], [2], etc.")
    L.append("def _clean(text):")
    L.append("    return _re.sub(r'\\[\\w+\\]', '', text).strip()")
    L.append("")
    L.append("DESKTOP = _os.path.join(_os.path.expanduser('~'), 'Desktop')")
    L.append("")
    L.append("# Patch json.loads for plain text (LLM often tries json.loads on plain text)")
    L.append("_orig_loads = _json.loads")
    L.append("def _safe_loads(s, *a, **kw):")
    L.append("    try:")
    L.append("        return _orig_loads(s, *a, **kw)")
    L.append("    except (_json.JSONDecodeError, ValueError):")
    L.append("        return _extract_paragraphs(s)")
    L.append("_json.loads = _safe_loads")
    L.append("# === End Pilot injection ===")
    L.append("")
    L.append("")

    return "\n".join(L)
